# https://hub.docker.com/_/postgres
version: '3'
services:
  postgres:
    image: postgres:13.2
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER       : ${PG_USER}
      POSTGRES_PASSWORD   : ${PG_PASS}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

